-- MySQL Script generated by MySQL Workbench
-- Mon Jun 23 21:17:00 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema store_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema store_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `store_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `store_db` ;

-- -----------------------------------------------------
-- Table `store_db`.`brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_db`.`brand` (
  `brand_id` INT NOT NULL,
  `brand_name` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`brand_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `store_db`.`colour`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_db`.`colour` (
  `colour_id` INT NOT NULL,
  `colour_name` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`colour_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `store_db`.`dress_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_db`.`dress_type` (
  `dress_id` INT NOT NULL,
  `dress_type` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`dress_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `store_db`.`length`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_db`.`length` (
  `length_id` INT NOT NULL,
  `length` INT NULL DEFAULT NULL,
  PRIMARY KEY (`length_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `store_db`.`neckline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_db`.`neckline` (
  `neckline_id` INT NOT NULL,
  `neckline_type` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`neckline_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `store_db`.`size_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_db`.`size_category` (
  `category_id` INT NOT NULL,
  `category_name` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `store_db`.`product_gender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_db`.`product_gender` (
  `product_gender_id` INT NOT NULL,
  `gender_name` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`product_gender_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `store_db`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_db`.`product_category` (
  `product_category_id` INT NOT NULL,
  `product_gender_id` INT NULL DEFAULT NULL,
  `category_name` VARCHAR(100) NULL DEFAULT NULL,
  `category_image` VARCHAR(100) NULL DEFAULT NULL,
  `category_description` VARCHAR(300) NULL DEFAULT NULL,
  `size_category_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`product_category_id`),
  INDEX `fk_prodcategory_gender` (`product_gender_id` ASC) VISIBLE,
  INDEX `fk_prodcategory_category` (`size_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_prodcategory_category`
    FOREIGN KEY (`size_category_id`)
    REFERENCES `store_db`.`size_category` (`category_id`),
  CONSTRAINT `fk_prodcategory_gender`
    FOREIGN KEY (`product_gender_id`)
    REFERENCES `store_db`.`product_gender` (`product_gender_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `store_db`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_db`.`product` (
  `product_id` INT NOT NULL,
  `product_name` VARCHAR(100) NULL DEFAULT NULL,
  `product_category_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `fk_prprodcategory` (`product_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_prprodcategory`
    FOREIGN KEY (`product_category_id`)
    REFERENCES `store_db`.`product_category` (`product_category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `store_db`.`season`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_db`.`season` (
  `season_id` INT NOT NULL,
  `season_name` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`season_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `store_db`.`sleeve_length`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_db`.`sleeve_length` (
  `sleeve_id` INT NOT NULL,
  `sleeve_length` INT NULL DEFAULT NULL,
  PRIMARY KEY (`sleeve_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `store_db`.`style`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_db`.`style` (
  `style_id` INT NOT NULL,
  `style_name` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`style_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `store_db`.`product_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_db`.`product_item` (
  `product_item_id` INT NOT NULL,
  `product_id` INT NULL DEFAULT NULL,
  `colour_id` INT NULL DEFAULT NULL,
  `original_price` INT NULL DEFAULT NULL,
  `sale_price` INT NULL DEFAULT NULL,
  `product_description` VARCHAR(300) NULL DEFAULT NULL,
  `brand_id` INT NULL DEFAULT NULL,
  `style_id` INT NULL DEFAULT NULL,
  `sleeve_id` INT NULL DEFAULT NULL,
  `neckline_id` INT NULL DEFAULT NULL,
  `dress_id` INT NULL DEFAULT NULL,
  `season_id` INT NULL DEFAULT NULL,
  `length_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`product_item_id`),
  INDEX `fk_proditem_colour` (`colour_id` ASC) VISIBLE,
  INDEX `fk_prod_item_brand` (`brand_id` ASC) VISIBLE,
  INDEX `fk_proditem_style` (`style_id` ASC) VISIBLE,
  INDEX `fk_proditem_sleeve` (`sleeve_id` ASC) VISIBLE,
  INDEX `fk_proditem_dress` (`dress_id` ASC) VISIBLE,
  INDEX `fk_proditem_season` (`season_id` ASC) VISIBLE,
  INDEX `fk_proditem_neckline` (`neckline_id` ASC) VISIBLE,
  INDEX `fk_proditem_length` (`length_id` ASC) VISIBLE,
  CONSTRAINT `fk_prod_item_brand`
    FOREIGN KEY (`brand_id`)
    REFERENCES `store_db`.`brand` (`brand_id`),
  CONSTRAINT `fk_proditem_colour`
    FOREIGN KEY (`colour_id`)
    REFERENCES `store_db`.`colour` (`colour_id`),
  CONSTRAINT `fk_proditem_dress`
    FOREIGN KEY (`dress_id`)
    REFERENCES `store_db`.`dress_type` (`dress_id`),
  CONSTRAINT `fk_proditem_length`
    FOREIGN KEY (`length_id`)
    REFERENCES `store_db`.`length` (`length_id`),
  CONSTRAINT `fk_proditem_neckline`
    FOREIGN KEY (`neckline_id`)
    REFERENCES `store_db`.`neckline` (`neckline_id`),
  CONSTRAINT `fk_proditem_season`
    FOREIGN KEY (`season_id`)
    REFERENCES `store_db`.`season` (`season_id`),
  CONSTRAINT `fk_proditem_sleeve`
    FOREIGN KEY (`sleeve_id`)
    REFERENCES `store_db`.`sleeve_length` (`sleeve_id`),
  CONSTRAINT `fk_proditem_style`
    FOREIGN KEY (`style_id`)
    REFERENCES `store_db`.`style` (`style_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `store_db`.`size_option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_db`.`size_option` (
  `size_id` INT NOT NULL,
  `size_name` VARCHAR(40) NULL DEFAULT NULL,
  `sort_order` INT NULL DEFAULT NULL,
  `size_category_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`size_id`),
  INDEX `fk_sizeoption_category` (`size_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_sizeoption_category`
    FOREIGN KEY (`size_category_id`)
    REFERENCES `store_db`.`size_category` (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `store_db`.`product_variation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_db`.`product_variation` (
  `variation_id` INT NOT NULL,
  `product_item_id` INT NULL DEFAULT NULL,
  `size_id` INT NULL DEFAULT NULL,
  `qty_in_stock` INT NULL DEFAULT NULL,
  PRIMARY KEY (`variation_id`),
  INDEX `fk_prodcar_prod_item` (`product_item_id` ASC) VISIBLE,
  INDEX `fk_prodvar_size` (`size_id` ASC) VISIBLE,
  CONSTRAINT `fk_prodcar_prod_item`
    FOREIGN KEY (`product_item_id`)
    REFERENCES `store_db`.`product_item` (`product_item_id`),
  CONSTRAINT `fk_prodvar_size`
    FOREIGN KEY (`size_id`)
    REFERENCES `store_db`.`size_option` (`size_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
